version: '3'
services:
  infzoom:
    container_name: infzoom
    restart: always
    build:
      context: ./infzoom
      dockerfile: Dockerfile
    ports:
     - '5999:8000'
    volumes:
     - './infzoom/src:/app'
     - './infzoom/images:/images'
     - './infzoom/output:/output'
     - './infzoom/audio:/audio'
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

  facedancer:
    # set container name
    container_name: facedancer

    restart: always

    # build the contaier
    build:
      context: .
      dockerfile: Dockerfile

    # set volumes
    volumes:
      - './src:/workspace'
      - './models/retinaface:/workspace/retinaface'
      - './models/arcface_model:/workspace/arcface_model'
      - './models/model_zoo:/workspace/model_zoo'
      - './src/results:/workspace/results'
    ports:
      - '8000:8000'

    # enable interactive terminal
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    # attach gpu to the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  redis_volume_data:
  db:
    driver: local
